server:
  port: 8083

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

  cloud:
    openfeign:
      client:
        config:
          product-service:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: BASIC
      circuitbreaker:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-secret@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNA==}

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  timelimiter:
    instances:
      product-service:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ecommerce.cartservice: DEBUG
