apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  EUREKA_HOST: "service-discovery"
  MYSQL_HOST: "mysql"
  MYSQL_USER: "ecommerce"
  REDIS_HOST: "redis"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ELASTICSEARCH_HOST: "elasticsearch"
  MONGODB_HOST: "mongodb"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_PASSWORD: "ecommerce_pass"
  JWT_SECRET: "bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNA=="
  REDIS_PASSWORD: ""
